name: freyja
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - alabaster=0.7.16
  - arrow-cpp=6.0.1
  - attr=2.5.1
  - aws-c-auth=0.6.8
  - aws-c-cal=0.5.12
  - aws-c-common=0.6.17
  - aws-c-compression=0.2.14
  - aws-c-event-stream=0.2.7
  - aws-c-http=0.6.10
  - aws-c-io=0.10.13
  - aws-c-mqtt=0.7.9
  - aws-c-s3=0.1.27
  - aws-c-sdkutils=0.1.1
  - aws-checksums=0.1.12
  - aws-crt-cpp=0.17.9
  - aws-sdk-cpp=1.9.154
  - babel=2.17.0
  - biopython=1.85
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clarabel=0.10.0
  - click=8.1.8
  - colorama=0.4.6
  - contourpy=1.3.0
  - cvxpy=1.6.2
  - cvxpy-base=1.6.2
  - cycler=0.12.1
  - docutils=0.21.2
  - epiweeks=2.3.0
  - fonttools=4.56.0
  - freetype=2.12.1
  - gawk=5.3.1
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - grpc-cpp=1.42.0
  - h2=4.2.0
  - hpack=4.1.0
  - htslib=1.17
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - isa-l=2.31.1
  - ivar=1.4.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.71
  - libcblas=3.9.0
  - libcbor=0.9.0
  - libcurl=7.87.0
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.6
  - libfido2=1.11.0
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libopenssl-static=3.0.7
  - libosqp=0.6.3
  - libpng=1.6.43
  - libprotobuf=3.18.3
  - libqdldl=0.1.7
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.15.0
  - libtiff=4.2.0
  - libudev1=257.3
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - mafft=7.526
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - mpfr=4.2.1
  - mpi=1.0
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - narwhals=1.27.1
  - ncurses=6.5
  - numpy=1.26.4
  - olefile=0.47
  - openjpeg=2.4.0
  - openmpi=4.1.2
  - openssh=9.1p1
  - openssl=1.1.1w
  - orc=1.7.1
  - osqp=0.6.7.post3
  - packaging=24.2
  - pandas=2.2.3
  - parquet-cpp=1.5.1
  - pillow=8.2.0
  - pip=25.0.1
  - plotly=6.0.0
  - pyarrow=6.0.1
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pysam=0.21.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.2
  - qdldl-python=0.1.7.post5
  - qhull=2020.2
  - re2=2021.11.01
  - readline=8.2
  - requests=2.32.3
  - s2n=1.3.0
  - samtools=1.18
  - scipy=1.13.1
  - scs=3.2.7.post2
  - seaborn-base=0.13.2
  - setuptools=75.8.2
  - six=1.17.0
  - snappy=1.1.10
  - snowballstemmer=2.2.0
  - sphinx=7.4.7
  - sphinx_rtd_theme=3.0.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - tk=8.6.13
  - tomli=2.2.1
  - tqdm=4.67.1
  - tzdata=2025a
  - ucsc-fatovcf=473
  - ucsc-stringify=472
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - usher=0.5.6
  - wheel=0.45.1
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
